/*
 * Face Detection And Recognition API
 *
 * Detect faces and recognize people from a specified image.
 *
 * API version: 0.1.9
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"errors"
	"net/http"
	"os"
)

// DefaultApiService is a service that implements the logic for the DefaultApiServicer
// This service should implement the business logic for every endpoint for the DefaultApi API.
// Include any external packages or services that will be required by this service.
type DefaultApiService struct {
}

// NewDefaultApiService creates a default api service
func NewDefaultApiService() DefaultApiServicer {
	return &DefaultApiService{}
}

// V1AuthPost - Returns whether specified user is identified.
func (s *DefaultApiService) V1AuthPost(ctx context.Context, fileName *os.File) (ImplResponse, error) {
	// TODO - update V1AuthPost with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, V1AuthPost200Response{}) or use other options such as http.Ok ...
	//return Response(200, V1AuthPost200Response{}), nil

	//TODO: Uncomment the next line to return response Response(403, V1AuthPost403Response{}) or use other options such as http.Ok ...
	//return Response(403, V1AuthPost403Response{}), nil

	//TODO: Uncomment the next line to return response Response(500, V1AuthPost500Response{}) or use other options such as http.Ok ...
	//return Response(500, V1AuthPost500Response{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("V1AuthPost method not implemented")
}
