/*
 * Face Detection And Recognition API
 *
 * Detect faces and recognize people from a specified image.
 *
 * API version: 0.1.9
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// ImplResponse response defines an error code with the associated body
type ImplResponse struct {
	Code int
	Body interface{}
}
