/*
 * Face Detection And Recognition API
 *
 * Detect faces and recognize people from a specified image.
 *
 * API version: 0.1.9
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type V1AuthPost200Response struct {
	Result string `json:"result,omitempty"`
}

// AssertV1AuthPost200ResponseRequired checks if the required fields are not zero-ed
func AssertV1AuthPost200ResponseRequired(obj V1AuthPost200Response) error {
	return nil
}

// AssertRecurseV1AuthPost200ResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of V1AuthPost200Response (e.g. [][]V1AuthPost200Response), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseV1AuthPost200ResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aV1AuthPost200Response, ok := obj.(V1AuthPost200Response)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertV1AuthPost200ResponseRequired(aV1AuthPost200Response)
	})
}
