/*
 * Face Detection And Recognition API
 *
 * Detect faces and recognize people from a specified image.
 *
 * API version: 0.1.9
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type V1AuthPost403Response struct {
	Code string `json:"code,omitempty"`

	Message string `json:"message,omitempty"`

	Description string `json:"description,omitempty"`
}

// AssertV1AuthPost403ResponseRequired checks if the required fields are not zero-ed
func AssertV1AuthPost403ResponseRequired(obj V1AuthPost403Response) error {
	return nil
}

// AssertRecurseV1AuthPost403ResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of V1AuthPost403Response (e.g. [][]V1AuthPost403Response), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseV1AuthPost403ResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aV1AuthPost403Response, ok := obj.(V1AuthPost403Response)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertV1AuthPost403ResponseRequired(aV1AuthPost403Response)
	})
}
