/*
 * Face Detection And Recognition API
 *
 * Detect faces and recognize people from a specified image.
 *
 * API version: 0.1.9
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type V1AuthPost500Response struct {
	Code string `json:"code,omitempty"`

	Message string `json:"message,omitempty"`

	Description string `json:"description,omitempty"`
}

// AssertV1AuthPost500ResponseRequired checks if the required fields are not zero-ed
func AssertV1AuthPost500ResponseRequired(obj V1AuthPost500Response) error {
	return nil
}

// AssertRecurseV1AuthPost500ResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of V1AuthPost500Response (e.g. [][]V1AuthPost500Response), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseV1AuthPost500ResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aV1AuthPost500Response, ok := obj.(V1AuthPost500Response)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertV1AuthPost500ResponseRequired(aV1AuthPost500Response)
	})
}
